name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Update Packages
        run: sudo apt update

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes || sudo apt-get install --fix-missing emacs-nox --yes

      - name: Build the site
        run: ./build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
